Remove-Item -Recurse -Force ".\Live"
.\extract.exe "C:\Program Files (x86)\Steam\steamapps\common\WildStar" ".\Live"
Move-Item ".\Live\UI\*" ".\Live\"
Remove-Item -Recurse -Force ".\Live\SpriteDocs"
Remove-Item -Recurse -Force ".\Live\Assets"
Remove-Item -Recurse -Force ".\Live\Houston"
Remove-Item -Recurse -Force ".\Live\HoustonSprEd"
Remove-Item -Recurse -Force ".\Live\Reticles"
Remove-Item -Recurse -Force ".\Live\Common"
Remove-Item -Recurse -Force ".\Live\Controls"
Remove-Item -Recurse -Force ".\Live\LuaDocData"
Remove-Item -Recurse -Force ".\Live\_OLD"
Remove-Item ".\Live\*.lua"
Remove-Item ".\Live\*.xml"
<#
Remove-Item -Recurse -Force ".\PTR"
Move-Item ".\PTR\UI\*" ".\PTR\"
.\extract.exe "B:\WildstarPTR" ".\PTR"
Remove-Item -Recurse -Force ".\PTR\SpriteDocs"
Remove-Item -Recurse -Force ".\PTR\Assets"
Remove-Item -Recurse -Force ".\PTR\Houston"
Remove-Item -Recurse -Force ".\PTR\HoustonSprEd"
Remove-Item -Recurse -Force ".\PTR\Reticles"
Remove-Item -Recurse -Force ".\PTR\Common"
Remove-Item -Recurse -Force ".\PTR\Controls"
Remove-Item -Recurse -Force ".\PTR\LuaDocData"
Remove-Item -Recurse -Force ".\PTR\_OLD"
Remove-Item ".\PTR\*.lua"
Remove-Item ".\PTR\*.xml"
#>